title: "Jira from scratch"
subtitle: "Un viaje desde el inicio por Jira"
author: "Juan Manuel Ibarra"
logo: images/logo-jira.png  # Opcional
execute:
  execute_notebooks: auto
launch_buttons:
  binderhub_url: "https://mybinder.org"
  thebe: true
html:
  favicon: images/favicon.ico  # Opcional
  use_issues_button: true
  use_repository_button: true
repository:
  url: https://github.com/tu-usuario/jira-interactivo
  path_to_book: ""
  branch: main